name: Tests
on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start Build script
        shell: powershell
        run: |
          .\build.ps1

      - name: Pester Tests
        shell: powershell
        run: |
          $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
          if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."} else {"Tests passed."}